export type Options = {
    value: string;
    label: string;
};

export const Points: string[] = ['From recruitment to employee relations, we offer expert HR services to streamline your processes and enhance productivity across all sectors.',
    'Our targeted programs connect graduates with meaningful job opportunities, helping to reduce unemployment rates and build a skilled workforce.',
    'Every individual deserves to be compensated fairly for their work. We advocate for fair wages and work tirelessly to eliminate underpayment and wage inequality.'];



export const jobTitlesOptions: Options[] = [
    { "value": "accountant", "label": "Accountant" },
    { "value": "actuary", "label": "Actuary" },
    { "value": "administrativeAssistant", "label": "Administrative Assistant" },
    { "value": "agriculturalExtensionWorker", "label": "Agricultural Extension Worker" },
    { "value": "airTrafficController", "label": "Air Traffic Controller" },
    { "value": "architect", "label": "Architect" },
    { "value": "areaSalesManager", "label": "Area Sales Manager" },
    { "value": "auditor", "label": "Auditor" },
    { "value": "bankingAndFinanceProfessional", "label": "Banking and Finance Professional" },
    { "value": "businessAnalyst", "label": "Business Analyst" },
    { "value": "businessDevelopmentManager", "label": "Business Development Manager" },
    { "value": "chemicalEngineer", "label": "Chemical Engineer" },
    { "value": "civilEngineer", "label": "Civil Engineer" },
    { "value": "computerProgrammer", "label": "Computer Programmer" },
    { "value": "constructionManager", "label": "Construction Manager" },
    { "value": "customerServiceRepresentative", "label": "Customer Service Representative" },
    { "value": "dataAnalyst", "label": "Data Analyst" },
    { "value": "databaseAdministrator", "label": "Database Administrator" },
    { "value": "dentist", "label": "Dentist" },
    { "value": "doctor", "label": "Doctor" },
    { "value": "electricalEngineer", "label": "Electrical Engineer" },
    { "value": "engineer", "label": "Engineer" },
    { "value": "entrepreneur", "label": "Entrepreneur" },
    { "value": "environmentalScientist", "label": "Environmental Scientist" },
    { "value": "executiveDirector", "label": "Executive Director" },
    { "value": "financialAnalyst", "label": "Financial Analyst" },
    { "value": "graphicDesigner", "label": "Graphic Designer" },
    { "value": "humanResourcesManager", "label": "Human Resources Manager" },
    { "value": "ictOfficer", "label": "ICT Officer" },
    { "value": "informationSecurityOfficer", "label": "Information Security Officer" },
    { "value": "insuranceBroker", "label": "Insurance Broker" },
    { "value": "investmentBanker", "label": "Investment Banker" },
    { "value": "itProjectManager", "label": "IT Project Manager" },
    { "value": "journalist", "label": "Journalist" },
    { "value": "lawyer", "label": "Lawyer" },
    { "value": "lecturer", "label": "Lecturer" },
    { "value": "logisticsAndSupplyChainManager", "label": "Logistics and Supply Chain Manager" },
    { "value": "managementConsultant", "label": "Management Consultant" },
    { "value": "marketingManager", "label": "Marketing Manager" },
    { "value": "mechanicalEngineer", "label": "Mechanical Engineer" },
    { "value": "medicalDoctor", "label": "Medical Doctor" },
    { "value": "networkAdministrator", "label": "Network Administrator" },
    { "value": "ngoProfessional", "label": "NGO Professional" },
    { "value": "nurse", "label": "Nurse" },
    { "value": "operationsManager", "label": "Operations Manager" },
    { "value": "pharmacist", "label": "Pharmacist" },
    { "value": "procurementOfficer", "label": "Procurement Officer" },
    { "value": "programmer", "label": "Programmer" },
    { "value": "projectManager", "label": "Project Manager" },
    { "value": "psychologist", "label": "Psychologist" },
    { "value": "quantitySurveyor", "label": "Quantity Surveyor" },
    { "value": "researcher", "label": "Researcher" },
    { "value": "salesManager", "label": "Sales Manager" },
    { "value": "softwareDeveloper", "label": "Software Developer" },
    { "value": "structuralEngineer", "label": "Structural Engineer" },
    { "value": "teacher", "label": "Teacher" },
    { "value": "telecommunicationsEngineer", "label": "Telecommunications Engineer" },
    { "value": "trainingAndDevelopmentOfficer", "label": "Training and Development Officer" },
    { "value": "webDeveloper", "label": "Web Developer" }
]

export const organizationNameOptions: Options[] = [
    { value: 'agriculture', label: 'Agriculture' },
    { value: 'miningAndQuarrying', label: 'Mining and Quarrying' },
    { value: 'manufacturing', label: 'Manufacturing' },
    { value: 'construction', label: 'Construction' },
    { value: 'trade', label: 'Trade' },
    { value: 'transportation', label: 'Transportation' },
    { value: 'accommodationAndFoodServices', label: 'Accommodation and Food Services' },
    { value: 'informationAndCommunication', label: 'Information and Communication' },
    { value: 'financeAndInsurance', label: 'Finance and Insurance' },
    { value: 'realEstate', label: 'Real Estate' },
    { value: 'professionalServices', label: 'Professional Services' },
    { value: 'education', label: 'Education' },
    { value: 'healthcare', label: 'Healthcare' },
    { value: 'artsAndEntertainment', label: 'Arts and Entertainment' },
    { value: 'tourism', label: 'Tourism' },
    { value: 'securityServices', label: 'Security Services' },
    { value: 'environmentalServices', label: 'Environmental Services' },
    { value: 'publicAdministration', label: 'Public Administration' },
    { value: 'nonProfit', label: 'Non-Profit' },
    { value: 'energyAndUtilities', label: 'Energy and Utilities' }
];

export const companyHeadquatersOptions: Options[] = [
    { value: 'abuja', label: 'Abuja' },
    { value: 'abia', label: 'Abia' },
    { value: 'adamawa', label: 'Adamawa' },
    { value: 'akwaIbom', label: 'Akwa Ibom' },
    { value: 'anambra', label: 'Anambra' },
    { value: 'bauchi', label: 'Bauchi' },
    { value: 'bayelsa', label: 'Bayelsa' },
    { value: 'benue', label: 'Benue' },
    { value: 'borno', label: 'Borno' },
    { value: 'crossRiver', label: 'Cross River' },
    { value: 'delta', label: 'Delta' },
    { value: 'ebonyi', label: 'Ebonyi' },
    { value: 'edo', label: 'Edo' },
    { value: 'ekiti', label: 'Ekiti' },
    { value: 'enugu', label: 'Enugu' },
    { value: 'gombe', label: 'Gombe' },
    { value: 'imo', label: 'Imo' },
    { value: 'jigawa', label: 'Jigawa' },
    { value: 'kaduna', label: 'Kaduna' },
    { value: 'kano', label: 'Kano' },
    { value: 'katsina', label: 'Katsina' },
    { value: 'kebbi', label: 'Kebbi' },
    { value: 'kogi', label: 'Kogi' },
    { value: 'kwara', label: 'Kwara' },
    { value: 'lagos', label: 'Lagos' },
    { value: 'nasarawa', label: 'Nasarawa' },
    { value: 'niger', label: 'Niger' },
    { value: 'ogun', label: 'Ogun' },
    { value: 'ondo', label: 'Ondo' },
    { value: 'osun', label: 'Osun' },
    { value: 'oyo', label: 'Oyo' },
    { value: 'plateau', label: 'Plateau' },
    { value: 'rivers', label: 'Rivers' },
    { value: 'sokoto', label: 'Sokoto' },
    { value: 'taraba', label: 'Taraba' },
    { value: 'yobe', label: 'Yobe' },
    { value: 'zamfara', label: 'Zamfara' }
];

export const companySizeOptions: Options[] = [
    { value: 'SMALL', label: '1 - 10' },
    { value: 'MEDIUM', label: '11 - 50' },
    { value: 'LARGE', label: '51 - 200' },
    { value: 'ENTERPRISE', label: '200+' }
];

export const queryResponseOptions: Options[] = [
    { value: 'absolutely', label: 'Absolutely' },
    { value: 'probably', label: 'Probably' },
    { value: 'Maybe', label: 'Maybe' },
    { value: 'Unlikely', label: 'Unlikely,' },
    { value: 'No', label: 'No,' }
];