// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import Hero from './Hero/index.svelte';
import NavigationHeading from './NavigationHeading/index.svelte';
import Onboarding from './Onboarding/index.svelte';
import Products from './Products/index.svelte';
import RealShowCase from './RealShowCase/index.svelte';
import RichText from './RichText/index.svelte';
import Sectors from './Sectors/index.svelte';
import Testimonials from './Testimonials/index.svelte';
import Tools from './Tools/index.svelte';

export const components = {
	bento: Bento,
	hero: Hero,
	navigation_heading: NavigationHeading,
	onboarding: Onboarding,
	products: Products,
	real_show_case: RealShowCase,
	rich_text: RichText,
	sectors: Sectors,
	testimonials: Testimonials,
	tools: Tools
};
