// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import BottomCta from './BottomCta/index.svelte';
import ChooseUs from './ChooseUs/index.svelte';
import Hero from './Hero/index.svelte';
import HeroStatistics from './HeroStatistics/index.svelte';
import MultipleFlexBoxes from './MultipleFlexBoxes/index.svelte';
import Navigation from './Navigation/index.svelte';
import NavigationHeading from './NavigationHeading/index.svelte';
import Onboarding from './Onboarding/index.svelte';
import Press from './Press/index.svelte';
import Products from './Products/index.svelte';
import RealShowCase from './RealShowCase/index.svelte';
import Reviews from './Reviews/index.svelte';
import RichText from './RichText/index.svelte';
import Sectors from './Sectors/index.svelte';
import Statistics from './Statistics/index.svelte';
import Switch from './Switch/index.svelte';
import Testimonials from './Testimonials/index.svelte';
import Tools from './Tools/index.svelte';
import VideoHero from './VideoHero/index.svelte';

export const components = {
	bento: Bento,
	bottom_cta: BottomCta,
	choose_us: ChooseUs,
	hero: Hero,
	hero_statistics: HeroStatistics,
	multiple_flex_boxes: MultipleFlexBoxes,
	navigation: Navigation,
	navigation_heading: NavigationHeading,
	onboarding: Onboarding,
	press: Press,
	products: Products,
	real_show_case: RealShowCase,
	reviews: Reviews,
	rich_text: RichText,
	sectors: Sectors,
	statistics: Statistics,
	switch: Switch,
	testimonials: Testimonials,
	tools: Tools,
	video_hero: VideoHero
};
