// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutUsDocumentDataSlicesSlice = never;

/**
 * Content for About_us documents
 */
interface AboutUsDocumentData {
	/**
	 * Slice Zone field in *About_us*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_us.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice> /**
	 * Meta Title field in *About_us*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: about_us.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *About_us*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: about_us.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *About_us*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_us.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * About_us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<AboutUsDocumentData>,
	'about_us',
	Lang
>;

type InsightsAndToolsDocumentDataSlicesSlice = never;

/**
 * Content for Insights and Tools documents
 */
interface InsightsAndToolsDocumentData {
	/**
	 * Slice Zone field in *Insights and Tools*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: insights_and_tools.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<InsightsAndToolsDocumentDataSlicesSlice> /**
	 * Meta Title field in *Insights and Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: insights_and_tools.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Insights and Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: insights_and_tools.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Insights and Tools*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: insights_and_tools.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Insights and Tools document from Prismic
 *
 * - **API ID**: `insights_and_tools`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InsightsAndToolsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<InsightsAndToolsDocumentData>,
	'insights_and_tools',
	Lang
>;

type LinkedPagesDocumentDataSlicesSlice = MultipleFlexBoxesSlice | PressSlice;

/**
 * Content for Linked Pages documents
 */
interface LinkedPagesDocumentData {
	/**
	 * Slice Zone field in *Linked Pages*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: linked_pages.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LinkedPagesDocumentDataSlicesSlice> /**
	 * Meta Title field in *Linked Pages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: linked_pages.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Linked Pages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: linked_pages.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Linked Pages*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: linked_pages.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Linked Pages document from Prismic
 *
 * - **API ID**: `linked_pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkedPagesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<LinkedPagesDocumentData>,
	'linked_pages',
	Lang
>;

type LoginDocumentDataSlicesSlice = never;

/**
 * Content for login documents
 */
interface LoginDocumentData {
	/**
	 * image field in *login*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: login.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * logo field in *login*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: login.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * another image field in *login*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: login.another_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	another_image: prismic.ImageField<never>;

	/**
	 * Background Image field in *login*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: login.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * Slice Zone field in *login*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: login.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LoginDocumentDataSlicesSlice> /**
	 * Meta Title field in *login*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: login.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *login*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: login.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *login*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: login.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * login document from Prismic
 *
 * - **API ID**: `login`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LoginDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<LoginDocumentData>,
	'login',
	Lang
>;

/**
 * Item in *Page → sections*
 */
export interface PageDocumentDataSectionsItem {
	/**
	 * heading field in *Page → sections*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Description field in *Page → sections*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

type PageDocumentDataSlicesSlice =
	| StatisticsSlice
	| HeroStatisticsSlice
	| BottomCtaSlice
	| VideoHeroSlice
	| PressSlice
	| ReviewsSlice
	| NavigationSlice
	| TestimonialsSlice
	| RealShowCaseSlice
	| BentoSlice
	| HeroSlice
	| ProductsSlice
	| ToolsSlice
	| OnboardingSlice
	| SectorsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * sections field in *Page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<PageDocumentDataSectionsItem>>;

	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * description field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * displayheading field in *Page*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: page.displayheading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	displayheading: prismic.BooleanField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

type ProductDocumentDataSlicesSlice = SwitchSlice | RichTextSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
	/**
	 * Product field in *Product*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	product: prismic.TitleField;

	/**
	 * Description field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * image field in *Product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Body field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Initials field in *Product*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.initials
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	initials: prismic.SelectField<'EOR' | 'PEO' | 'ERT' | 'CSO'>;

	/**
	 * Slice Zone field in *Product*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
	 * Meta Title field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: product.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: product.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProductDocumentData>,
	'product',
	Lang
>;

/**
 * Item in *Settings → Policies*
 */
export interface SettingsDocumentDataPoliciesItem {
	/**
	 * policy_link field in *Settings → Policies*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.policies[].policy_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	policy_link: prismic.LinkField;

	/**
	 * policy label field in *Settings → Policies*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.policies[].policy_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	policy_label: prismic.KeyTextField;
}

type SettingsDocumentDataSlicesSlice = NavigationHeadingSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Site Title field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	site_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * OG Image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.og_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;

	/**
	 * Policies field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.policies[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	policies: prismic.GroupField<Simplify<SettingsDocumentDataPoliciesItem>>;

	/**
	 * Slice Zone field in *Settings*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

type SettingsPagesDocumentDataSlicesSlice = never;

/**
 * Content for Settings Pages documents
 */
interface SettingsPagesDocumentData {
	/**
	 * Slice Zone field in *Settings Pages*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings_pages.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SettingsPagesDocumentDataSlicesSlice> /**
	 * Meta Title field in *Settings Pages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: settings_pages.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Settings Pages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: settings_pages.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Settings Pages*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings_pages.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Settings Pages document from Prismic
 *
 * - **API ID**: `settings_pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsPagesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SettingsPagesDocumentData>,
	'settings_pages',
	Lang
>;

type ShowcasetypeDocumentDataSlicesSlice = never;

/**
 * Content for ShowCaseType documents
 */
interface ShowcasetypeDocumentData {
	/**
	 * Slice Zone field in *ShowCaseType*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcasetype.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ShowcasetypeDocumentDataSlicesSlice>;
}

/**
 * ShowCaseType document from Prismic
 *
 * - **API ID**: `showcasetype`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShowcasetypeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ShowcasetypeDocumentData>,
	'showcasetype',
	Lang
>;

/**
 * Item in *signup → subsection*
 */
export interface SignupDocumentDataSubsectionItem {
	/**
	 * Heading field in *signup → subsection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.subsection[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *signup → subsection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.subsection[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Item in *signup → buttons*
 */
export interface SignupDocumentDataButtonsItem {
	/**
	 * image field in *signup → buttons*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.buttons[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Header field in *signup → buttons*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.buttons[].header
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	header: prismic.RichTextField;

	/**
	 * Body field in *signup → buttons*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.buttons[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * userType field in *signup → buttons*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.buttons[].usertype
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	usertype: prismic.SelectField<'Professional' | 'Company' | 'Partner'>;
}

type SignupDocumentDataSlicesSlice = never;

/**
 * Content for signup documents
 */
interface SignupDocumentData {
	/**
	 * Heading field in *signup*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * subheading field in *signup*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.subheading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheading: prismic.RichTextField;

	/**
	 * image field in *signup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * subsection field in *signup*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.subsection[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	subsection: prismic.GroupField<Simplify<SignupDocumentDataSubsectionItem>>;

	/**
	 * Question field in *signup*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.question
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	question: prismic.RichTextField;

	/**
	 * buttons field in *signup*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.buttons[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	buttons: prismic.GroupField<Simplify<SignupDocumentDataButtonsItem>>;

	/**
	 * Slice Zone field in *signup*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SignupDocumentDataSlicesSlice> /**
	 * Meta Title field in *signup*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: signup.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *signup*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: signup.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *signup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: signup.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * signup document from Prismic
 *
 * - **API ID**: `signup`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SignupDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SignupDocumentData>,
	'signup',
	Lang
>;

type ToolsDocumentDataSlicesSlice = SwitchSlice | RichTextSlice;

/**
 * Content for Tools documents
 */
interface ToolsDocumentData {
	/**
	 * Tool field in *Tools*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.tool
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tool: prismic.TitleField;

	/**
	 * Description field in *Tools*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *Tools*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Body field in *Tools*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Slice Zone field in *Tools*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ToolsDocumentDataSlicesSlice> /**
	 * Meta Title field in *Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: tools.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: tools.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Tools*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Tools document from Prismic
 *
 * - **API ID**: `tools`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ToolsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ToolsDocumentData>,
	'tools',
	Lang
>;

type WhatWeThinkDocumentDataSlicesSlice = RichTextSlice | ChooseUsSlice | VideoHeroSlice;

/**
 * Content for what we think documents
 */
interface WhatWeThinkDocumentData {
	/**
	 * Slice Zone field in *what we think*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: what_we_think.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<WhatWeThinkDocumentDataSlicesSlice> /**
	 * Meta Title field in *what we think*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: what_we_think.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *what we think*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: what_we_think.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *what we think*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: what_we_think.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * what we think document from Prismic
 *
 * - **API ID**: `what_we_think`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WhatWeThinkDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<WhatWeThinkDocumentData>,
	'what_we_think',
	Lang
>;

export type AllDocumentTypes =
	| AboutUsDocument
	| InsightsAndToolsDocument
	| LinkedPagesDocument
	| LoginDocument
	| PageDocument
	| ProductDocument
	| SettingsDocument
	| SettingsPagesDocument
	| ShowcasetypeDocument
	| SignupDocument
	| ToolsDocument
	| WhatWeThinkDocument;

/**
 * Item in *Bento → Default → Primary → Four Divisions*
 */
export interface BentoSliceDefaultPrimaryFourDivisionsItem {
	/**
	 * title field in *Bento → Default → Primary → Four Divisions*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.four_divisions[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Body field in *Bento → Default → Primary → Four Divisions*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.four_divisions[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Image field in *Bento → Default → Primary → Four Divisions*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.four_divisions[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Wide field in *Bento → Default → Primary → Four Divisions*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: bento.default.primary.four_divisions[].wide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	wide: prismic.BooleanField;

	/**
	 * Link field in *Bento → Default → Primary → Four Divisions*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.four_divisions[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * link_label field in *Bento → Default → Primary → Four Divisions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.four_divisions[].link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_label: prismic.KeyTextField;
}

/**
 * Primary content in *Bento → Default → Primary*
 */
export interface BentoSliceDefaultPrimary {
	/**
	 * Heading field in *Bento → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Bento → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Four Divisions field in *Bento → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.four_divisions[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	four_divisions: prismic.GroupField<Simplify<BentoSliceDefaultPrimaryFourDivisionsItem>>;
}

/**
 * Default variation for Bento Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BentoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BentoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Bento*
 */
type BentoSliceVariation = BentoSliceDefault;

/**
 * Bento Shared Slice
 *
 * - **API ID**: `bento`
 * - **Description**: Bento
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BentoSlice = prismic.SharedSlice<'bento', BentoSliceVariation>;

/**
 * Primary content in *BottomCta → Default → Primary*
 */
export interface BottomCtaSliceDefaultPrimary {
	/**
	 * image field in *BottomCta → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bottom_cta.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Heading field in *BottomCta → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bottom_cta.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * body field in *BottomCta → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bottom_cta.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * link to signup field in *BottomCta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bottom_cta.default.primary.link_to_signup
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_to_signup: prismic.LinkField;
}

/**
 * Default variation for BottomCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BottomCtaSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BottomCtaSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BottomCta*
 */
type BottomCtaSliceVariation = BottomCtaSliceDefault;

/**
 * BottomCta Shared Slice
 *
 * - **API ID**: `bottom_cta`
 * - **Description**: BottomCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BottomCtaSlice = prismic.SharedSlice<'bottom_cta', BottomCtaSliceVariation>;

/**
 * Item in *ChooseUs → Default → Primary → benefits*
 */
export interface ChooseUsSliceDefaultPrimaryBenefitsItem {
	/**
	 * image field in *ChooseUs → Default → Primary → benefits*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: choose_us.default.primary.benefits[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Heading field in *ChooseUs → Default → Primary → benefits*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: choose_us.default.primary.benefits[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Body field in *ChooseUs → Default → Primary → benefits*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: choose_us.default.primary.benefits[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *ChooseUs → Default → Primary*
 */
export interface ChooseUsSliceDefaultPrimary {
	/**
	 * Heading field in *ChooseUs → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: choose_us.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * body field in *ChooseUs → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: choose_us.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * benefits field in *ChooseUs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: choose_us.default.primary.benefits[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	benefits: prismic.GroupField<Simplify<ChooseUsSliceDefaultPrimaryBenefitsItem>>;
}

/**
 * Default variation for ChooseUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChooseUsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ChooseUsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ChooseUs*
 */
type ChooseUsSliceVariation = ChooseUsSliceDefault;

/**
 * ChooseUs Shared Slice
 *
 * - **API ID**: `choose_us`
 * - **Description**: ChooseUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChooseUsSlice = prismic.SharedSlice<'choose_us', ChooseUsSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Points*
 */
export interface HeroSliceDefaultPrimaryPointsItem {
	/**
	 * point field in *Hero → Default → Primary → Points*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.points[].point
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	point: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Hero Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hero_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image: prismic.ImageField<never>;

	/**
	 * Points field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.points[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	points: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryPointsItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *HeroStatistics → Default → Primary → Statistic*
 */
export interface HeroStatisticsSliceDefaultPrimaryStatisticItem {
	/**
	 * Number field in *HeroStatistics → Default → Primary → Statistic*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statistics.default.primary.statistic[].number
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	number: prismic.RichTextField;

	/**
	 * Body field in *HeroStatistics → Default → Primary → Statistic*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statistics.default.primary.statistic[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *HeroStatistics → Default → Primary*
 */
export interface HeroStatisticsSliceDefaultPrimary {
	/**
	 * Image field in *HeroStatistics → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statistics.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Statistic field in *HeroStatistics → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statistics.default.primary.statistic[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	statistic: prismic.GroupField<Simplify<HeroStatisticsSliceDefaultPrimaryStatisticItem>>;
}

/**
 * Default variation for HeroStatistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroStatisticsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroStatisticsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroStatistics*
 */
type HeroStatisticsSliceVariation = HeroStatisticsSliceDefault;

/**
 * HeroStatistics Shared Slice
 *
 * - **API ID**: `hero_statistics`
 * - **Description**: HeroStatistics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroStatisticsSlice = prismic.SharedSlice<
	'hero_statistics',
	HeroStatisticsSliceVariation
>;

/**
 * Item in *MultipleFlexBoxes → Default → Primary → Boxes*
 */
export interface MultipleFlexBoxesSliceDefaultPrimaryBoxesItem {}

/**
 * Primary content in *MultipleFlexBoxes → Default → Primary*
 */
export interface MultipleFlexBoxesSliceDefaultPrimary {
	/**
	 * Heading field in *MultipleFlexBoxes → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: multiple_flex_boxes.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Boxes field in *MultipleFlexBoxes → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: multiple_flex_boxes.default.primary.boxes[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	boxes: prismic.GroupField<Simplify<MultipleFlexBoxesSliceDefaultPrimaryBoxesItem>>;
}

/**
 * Default variation for MultipleFlexBoxes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultipleFlexBoxesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MultipleFlexBoxesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *MultipleFlexBoxes*
 */
type MultipleFlexBoxesSliceVariation = MultipleFlexBoxesSliceDefault;

/**
 * MultipleFlexBoxes Shared Slice
 *
 * - **API ID**: `multiple_flex_boxes`
 * - **Description**: MultipleFlexBoxes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultipleFlexBoxesSlice = prismic.SharedSlice<
	'multiple_flex_boxes',
	MultipleFlexBoxesSliceVariation
>;

/**
 * Item in *Navigation → Default → Primary → access to*
 */
export interface NavigationSliceDefaultPrimaryAccessToItem {
	/**
	 * points field in *Navigation → Default → Primary → access to*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.access_to[].points
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	points: prismic.RichTextField;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
	/**
	 * Heading field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * image field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * access to field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.access_to[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	access_to: prismic.GroupField<Simplify<NavigationSliceDefaultPrimaryAccessToItem>>;

	/**
	 * link field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * subheading field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheading: prismic.RichTextField;

	/**
	 * label field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<'navigation', NavigationSliceVariation>;

/**
 * Item in *NavigationHeading → Default → Primary → Navigation*
 */
export interface NavigationHeadingSliceDefaultPrimaryNavigationItem {
	/**
	 * nav_link field in *NavigationHeading → Default → Primary → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_heading.default.primary.navigation[].nav_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	nav_link: prismic.LinkField;
}

/**
 * Primary content in *NavigationHeading → Default → Primary*
 */
export interface NavigationHeadingSliceDefaultPrimary {
	/**
	 * Navigation Heading field in *NavigationHeading → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_heading.default.primary.navigation_heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	navigation_heading: prismic.KeyTextField;

	/**
	 * Navigation field in *NavigationHeading → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_heading.default.primary.navigation[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<NavigationHeadingSliceDefaultPrimaryNavigationItem>>;
}

/**
 * Default variation for NavigationHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationHeadingSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationHeadingSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *NavigationHeading*
 */
type NavigationHeadingSliceVariation = NavigationHeadingSliceDefault;

/**
 * NavigationHeading Shared Slice
 *
 * - **API ID**: `navigation_heading`
 * - **Description**: NavigationHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationHeadingSlice = prismic.SharedSlice<
	'navigation_heading',
	NavigationHeadingSliceVariation
>;

/**
 * Item in *Onboarding → Default → Primary → Steps*
 */
export interface OnboardingSliceDefaultPrimaryStepsItem {
	/**
	 * Heading field in *Onboarding → Default → Primary → Steps*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: onboarding.default.primary.steps[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Onboarding → Default → Primary → Steps*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: onboarding.default.primary.steps[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * image field in *Onboarding → Default → Primary → Steps*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: onboarding.default.primary.steps[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Onboarding → Default → Primary*
 */
export interface OnboardingSliceDefaultPrimary {
	/**
	 * Steps field in *Onboarding → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: onboarding.default.primary.steps[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	steps: prismic.GroupField<Simplify<OnboardingSliceDefaultPrimaryStepsItem>>;

	/**
	 * Heading field in *Onboarding → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: onboarding.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * image field in *Onboarding → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: onboarding.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Onboarding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnboardingSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<OnboardingSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Onboarding*
 */
type OnboardingSliceVariation = OnboardingSliceDefault;

/**
 * Onboarding Shared Slice
 *
 * - **API ID**: `onboarding`
 * - **Description**: Onboarding
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnboardingSlice = prismic.SharedSlice<'onboarding', OnboardingSliceVariation>;

/**
 * Item in *Press → Default → Primary → News Box*
 */
export interface PressSliceDefaultPrimaryNewsBoxItem {
	/**
	 * Heading field in *Press → Default → Primary → News Box*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.news_box[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * image field in *Press → Default → Primary → News Box*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.news_box[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * link field in *Press → Default → Primary → News Box*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.news_box[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Press → With Subheading → Primary → News Box*
 */
export interface PressSliceWithSubheadingPrimaryNewsBoxItem {
	/**
	 * Heading field in *Press → With Subheading → Primary → News Box*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.news_box[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * body field in *Press → With Subheading → Primary → News Box*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.news_box[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * link field in *Press → With Subheading → Primary → News Box*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.news_box[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Press → Default → Primary*
 */
export interface PressSliceDefaultPrimary {
	/**
	 * Heading field in *Press → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * body field in *Press → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * News Box field in *Press → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.news_box[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	news_box: prismic.GroupField<Simplify<PressSliceDefaultPrimaryNewsBoxItem>>;

	/**
	 * icon field in *Press → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.default.primary.icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<'Label' | 'BookMark'>;
}

/**
 * Default variation for Press Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PressSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PressSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Press → With Subheading → Primary*
 */
export interface PressSliceWithSubheadingPrimary {
	/**
	 * Heading field in *Press → With Subheading → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * body field in *Press → With Subheading → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * News Box field in *Press → With Subheading → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.news_box[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	news_box: prismic.GroupField<Simplify<PressSliceWithSubheadingPrimaryNewsBoxItem>>;

	/**
	 * icon field in *Press → With Subheading → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: press.withSubheading.primary.icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<'Label' | 'BookMark'>;
}

/**
 * With Subheading variation for Press Slice
 *
 * - **API ID**: `withSubheading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PressSliceWithSubheading = prismic.SharedSliceVariation<
	'withSubheading',
	Simplify<PressSliceWithSubheadingPrimary>,
	never
>;

/**
 * Slice variation for *Press*
 */
type PressSliceVariation = PressSliceDefault | PressSliceWithSubheading;

/**
 * Press Shared Slice
 *
 * - **API ID**: `press`
 * - **Description**: Press
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PressSlice = prismic.SharedSlice<'press', PressSliceVariation>;

/**
 * Item in *Products → Default → Primary → Products*
 */
export interface ProductsSliceDefaultPrimaryProductsItem {
	/**
	 * Product field in *Products → Default → Primary → Products*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.products[].product
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	product: prismic.ContentRelationshipField<'product'>;

	/**
	 * Initials field in *Products → Default → Primary → Products*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.products[].initials
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	initials: prismic.SelectField<'EOR' | 'PEO' | 'ERT' | 'CSO'>;
}

/**
 * Primary content in *Products → Default → Primary*
 */
export interface ProductsSliceDefaultPrimary {
	/**
	 * Title field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Heading field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Body field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Link to Products field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.link_to_products
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_to_products: prismic.LinkField;

	/**
	 * link label field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_label: prismic.KeyTextField;

	/**
	 * Products field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.products[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	products: prismic.GroupField<Simplify<ProductsSliceDefaultPrimaryProductsItem>>;

	/**
	 * subheading field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheading: prismic.RichTextField;

	/**
	 * Dashboard Image field in *Products → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products.default.primary.dashboard_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	dashboard_image: prismic.ImageField<never>;
}

/**
 * Default variation for Products Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProductsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Products*
 */
type ProductsSliceVariation = ProductsSliceDefault;

/**
 * Products Shared Slice
 *
 * - **API ID**: `products`
 * - **Description**: Products
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSlice = prismic.SharedSlice<'products', ProductsSliceVariation>;

/**
 * Item in *RealShowCase → Default → Primary → Switchable Divs*
 */
export interface RealShowCaseSliceDefaultPrimarySwitchableDivsItem {
	/**
	 * Description field in *RealShowCase → Default → Primary → Switchable Divs*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: real_show_case.default.primary.switchable_divs[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *RealShowCase → Default → Primary → Switchable Divs*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: real_show_case.default.primary.switchable_divs[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Icon Image field in *RealShowCase → Default → Primary → Switchable Divs*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: real_show_case.default.primary.switchable_divs[].icon_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon_image: prismic.ImageField<never>;

	/**
	 * label field in *RealShowCase → Default → Primary → Switchable Divs*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: real_show_case.default.primary.switchable_divs[].label
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	label: prismic.SelectField<'Hiring' | 'Payroll' | 'Training' | 'Compliance' | 'Software'>;
}

/**
 * Primary content in *RealShowCase → Default → Primary*
 */
export interface RealShowCaseSliceDefaultPrimary {
	/**
	 * Heading field in *RealShowCase → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: real_show_case.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Switchable Divs field in *RealShowCase → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: real_show_case.default.primary.switchable_divs[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	switchable_divs: prismic.GroupField<Simplify<RealShowCaseSliceDefaultPrimarySwitchableDivsItem>>;
}

/**
 * Default variation for RealShowCase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RealShowCaseSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RealShowCaseSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RealShowCase*
 */
type RealShowCaseSliceVariation = RealShowCaseSliceDefault;

/**
 * RealShowCase Shared Slice
 *
 * - **API ID**: `real_show_case`
 * - **Description**: RealShowCase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RealShowCaseSlice = prismic.SharedSlice<'real_show_case', RealShowCaseSliceVariation>;

/**
 * Item in *Reviews → Default → Primary → review boxes*
 */
export interface ReviewsSliceDefaultPrimaryReviewBoxesItem {
	/**
	 * review field in *Reviews → Default → Primary → review boxes*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.default.primary.review_boxes[].review
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	review: prismic.RichTextField;

	/**
	 * reviewer field in *Reviews → Default → Primary → review boxes*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.default.primary.review_boxes[].reviewer
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	reviewer: prismic.RichTextField;

	/**
	 * background color field in *Reviews → Default → Primary → review boxes*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.default.primary.review_boxes[].background_color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	background_color: prismic.SelectField<'#9999FF' | '#FF9A00' | '#9266cc' | '#31A8FF'>;
}

/**
 * Primary content in *Reviews → Default → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
	/**
	 * Heading field in *Reviews → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * review boxes field in *Reviews → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.default.primary.review_boxes[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	review_boxes: prismic.GroupField<Simplify<ReviewsSliceDefaultPrimaryReviewBoxesItem>>;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ReviewsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<'reviews', ReviewsSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Item in *Sectors → Default → Primary → choose us*
 */
export interface SectorsSliceDefaultPrimaryChooseUsItem {
	/**
	 * image field in *Sectors → Default → Primary → choose us*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.choose_us[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * heading field in *Sectors → Default → Primary → choose us*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.choose_us[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Sectors → Default → Primary → choose us*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.choose_us[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Item in *Sectors → Default → Primary → Economic Sector*
 */
export interface SectorsSliceDefaultPrimaryEconomicSectorItem {
	/**
	 * image field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Background Imge field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].background_imge
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_imge: prismic.ImageField<never>;

	/**
	 * subheading field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].subheading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheading: prismic.RichTextField;

	/**
	 * Challenges field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].challenges
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	challenges: prismic.RichTextField;

	/**
	 * solutions field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].solutions
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	solutions: prismic.RichTextField;

	/**
	 * Challenges Heading field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].challenges_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	challenges_heading: prismic.RichTextField;

	/**
	 * Solutions Heading field in *Sectors → Default → Primary → Economic Sector*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[].solutions_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	solutions_heading: prismic.RichTextField;
}

/**
 * Primary content in *Sectors → Default → Primary*
 */
export interface SectorsSliceDefaultPrimary {
	/**
	 * Heading field in *Sectors → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * choose us field in *Sectors → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.choose_us[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	choose_us: prismic.GroupField<Simplify<SectorsSliceDefaultPrimaryChooseUsItem>>;

	/**
	 * Economic Sector field in *Sectors → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sectors.default.primary.economic_sector[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	economic_sector: prismic.GroupField<Simplify<SectorsSliceDefaultPrimaryEconomicSectorItem>>;
}

/**
 * Default variation for Sectors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectorsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SectorsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Sectors*
 */
type SectorsSliceVariation = SectorsSliceDefault;

/**
 * Sectors Shared Slice
 *
 * - **API ID**: `sectors`
 * - **Description**: Sectors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectorsSlice = prismic.SharedSlice<'sectors', SectorsSliceVariation>;

/**
 * Item in *Statistics → Default → Primary → Statistics*
 */
export interface StatisticsSliceDefaultPrimaryStatisticsItem {
	/**
	 * Header field in *Statistics → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.default.primary.statistics[].header
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	header: prismic.RichTextField;

	/**
	 * Body field in *Statistics → Default → Primary → Statistics*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.default.primary.statistics[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *Statistics → Default → Primary*
 */
export interface StatisticsSliceDefaultPrimary {
	/**
	 * Heading field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Statistics field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.default.primary.statistics[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	statistics: prismic.GroupField<Simplify<StatisticsSliceDefaultPrimaryStatisticsItem>>;
}

/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<StatisticsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Statistics*
 */
type StatisticsSliceVariation = StatisticsSliceDefault;

/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: Statistics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSlice = prismic.SharedSlice<'statistics', StatisticsSliceVariation>;

/**
 * Item in *Switch → Default → Primary → subsection*
 */
export interface SwitchSliceDefaultPrimarySubsectionItem {
	/**
	 * Heading field in *Switch → Default → Primary → subsection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: switch.default.primary.subsection[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * subheading field in *Switch → Default → Primary → subsection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: switch.default.primary.subsection[].subheading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheading: prismic.RichTextField;

	/**
	 * sub body field in *Switch → Default → Primary → subsection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: switch.default.primary.subsection[].sub_body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	sub_body: prismic.RichTextField;

	/**
	 * image field in *Switch → Default → Primary → subsection*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: switch.default.primary.subsection[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Switch → Default → Primary*
 */
export interface SwitchSliceDefaultPrimary {
	/**
	 * Heading field in *Switch → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: switch.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * subsection field in *Switch → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: switch.default.primary.subsection[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	subsection: prismic.GroupField<Simplify<SwitchSliceDefaultPrimarySubsectionItem>>;
}

/**
 * Default variation for Switch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwitchSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SwitchSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Switch*
 */
type SwitchSliceVariation = SwitchSliceDefault;

/**
 * Switch Shared Slice
 *
 * - **API ID**: `switch`
 * - **Description**: Switch
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwitchSlice = prismic.SharedSlice<'switch', SwitchSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
	/**
	 * image field in *Testimonials → Default → Primary → testimonials*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.testimonials[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Name field in *Testimonials → Default → Primary → testimonials*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.testimonials[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;

	/**
	 * comment field in *Testimonials → Default → Primary → testimonials*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.testimonials[].comment
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	comment: prismic.RichTextField;

	/**
	 * position field in *Testimonials → Default → Primary → testimonials*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.testimonials[].position
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	position: prismic.RichTextField;

	/**
	 * linkedin link field in *Testimonials → Default → Primary → testimonials*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.testimonials[].linkedin_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	linkedin_link: prismic.LinkField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * testimonials field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.testimonials[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	testimonials: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TestimonialsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<'testimonials', TestimonialsSliceVariation>;

/**
 * Item in *Tools → Default → Primary → Tools*
 */
export interface ToolsSliceDefaultPrimaryToolsItem {
	/**
	 * tool field in *Tools → Default → Primary → Tools*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.tools[].tool
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	tool: prismic.ContentRelationshipField<'tools'>;
}

/**
 * Primary content in *Tools → Default → Primary*
 */
export interface ToolsSliceDefaultPrimary {
	/**
	 * Heading field in *Tools → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Body field in *Tools → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Link to Tools field in *Tools → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.link_to_tools
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_to_tools: prismic.LinkField;

	/**
	 * Tools field in *Tools → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.tools[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	tools: prismic.GroupField<Simplify<ToolsSliceDefaultPrimaryToolsItem>>;

	/**
	 * label field in *Tools → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * dealInsight Image field in *Tools → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.default.primary.dealinsight_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	dealinsight_image: prismic.ImageField<never>;
}

/**
 * Default variation for Tools Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ToolsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ToolsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Tools*
 */
type ToolsSliceVariation = ToolsSliceDefault;

/**
 * Tools Shared Slice
 *
 * - **API ID**: `tools`
 * - **Description**: Tools
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ToolsSlice = prismic.SharedSlice<'tools', ToolsSliceVariation>;

/**
 * Primary content in *VideoHero → Default → Primary*
 */
export interface VideoHeroSliceDefaultPrimary {
	/**
	 * video field in *VideoHero → Default → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_hero.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video: prismic.EmbedField;

	/**
	 * Heading field in *VideoHero → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Body field in *VideoHero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_hero.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Cta Link field in *VideoHero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;
}

/**
 * Default variation for VideoHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoHeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoHeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VideoHero*
 */
type VideoHeroSliceVariation = VideoHeroSliceDefault;

/**
 * VideoHero Shared Slice
 *
 * - **API ID**: `video_hero`
 * - **Description**: VideoHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoHeroSlice = prismic.SharedSlice<'video_hero', VideoHeroSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			AboutUsDocument,
			AboutUsDocumentData,
			AboutUsDocumentDataSlicesSlice,
			InsightsAndToolsDocument,
			InsightsAndToolsDocumentData,
			InsightsAndToolsDocumentDataSlicesSlice,
			LinkedPagesDocument,
			LinkedPagesDocumentData,
			LinkedPagesDocumentDataSlicesSlice,
			LoginDocument,
			LoginDocumentData,
			LoginDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSectionsItem,
			PageDocumentDataSlicesSlice,
			ProductDocument,
			ProductDocumentData,
			ProductDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataPoliciesItem,
			SettingsDocumentDataSlicesSlice,
			SettingsPagesDocument,
			SettingsPagesDocumentData,
			SettingsPagesDocumentDataSlicesSlice,
			ShowcasetypeDocument,
			ShowcasetypeDocumentData,
			ShowcasetypeDocumentDataSlicesSlice,
			SignupDocument,
			SignupDocumentData,
			SignupDocumentDataSubsectionItem,
			SignupDocumentDataButtonsItem,
			SignupDocumentDataSlicesSlice,
			ToolsDocument,
			ToolsDocumentData,
			ToolsDocumentDataSlicesSlice,
			WhatWeThinkDocument,
			WhatWeThinkDocumentData,
			WhatWeThinkDocumentDataSlicesSlice,
			AllDocumentTypes,
			BentoSlice,
			BentoSliceDefaultPrimaryFourDivisionsItem,
			BentoSliceDefaultPrimary,
			BentoSliceVariation,
			BentoSliceDefault,
			BottomCtaSlice,
			BottomCtaSliceDefaultPrimary,
			BottomCtaSliceVariation,
			BottomCtaSliceDefault,
			ChooseUsSlice,
			ChooseUsSliceDefaultPrimaryBenefitsItem,
			ChooseUsSliceDefaultPrimary,
			ChooseUsSliceVariation,
			ChooseUsSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimaryPointsItem,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroStatisticsSlice,
			HeroStatisticsSliceDefaultPrimaryStatisticItem,
			HeroStatisticsSliceDefaultPrimary,
			HeroStatisticsSliceVariation,
			HeroStatisticsSliceDefault,
			MultipleFlexBoxesSlice,
			MultipleFlexBoxesSliceDefaultPrimaryBoxesItem,
			MultipleFlexBoxesSliceDefaultPrimary,
			MultipleFlexBoxesSliceVariation,
			MultipleFlexBoxesSliceDefault,
			NavigationSlice,
			NavigationSliceDefaultPrimaryAccessToItem,
			NavigationSliceDefaultPrimary,
			NavigationSliceVariation,
			NavigationSliceDefault,
			NavigationHeadingSlice,
			NavigationHeadingSliceDefaultPrimaryNavigationItem,
			NavigationHeadingSliceDefaultPrimary,
			NavigationHeadingSliceVariation,
			NavigationHeadingSliceDefault,
			OnboardingSlice,
			OnboardingSliceDefaultPrimaryStepsItem,
			OnboardingSliceDefaultPrimary,
			OnboardingSliceVariation,
			OnboardingSliceDefault,
			PressSlice,
			PressSliceDefaultPrimaryNewsBoxItem,
			PressSliceDefaultPrimary,
			PressSliceWithSubheadingPrimaryNewsBoxItem,
			PressSliceWithSubheadingPrimary,
			PressSliceVariation,
			PressSliceDefault,
			PressSliceWithSubheading,
			ProductsSlice,
			ProductsSliceDefaultPrimaryProductsItem,
			ProductsSliceDefaultPrimary,
			ProductsSliceVariation,
			ProductsSliceDefault,
			RealShowCaseSlice,
			RealShowCaseSliceDefaultPrimarySwitchableDivsItem,
			RealShowCaseSliceDefaultPrimary,
			RealShowCaseSliceVariation,
			RealShowCaseSliceDefault,
			ReviewsSlice,
			ReviewsSliceDefaultPrimaryReviewBoxesItem,
			ReviewsSliceDefaultPrimary,
			ReviewsSliceVariation,
			ReviewsSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			SectorsSlice,
			SectorsSliceDefaultPrimaryChooseUsItem,
			SectorsSliceDefaultPrimaryEconomicSectorItem,
			SectorsSliceDefaultPrimary,
			SectorsSliceVariation,
			SectorsSliceDefault,
			StatisticsSlice,
			StatisticsSliceDefaultPrimaryStatisticsItem,
			StatisticsSliceDefaultPrimary,
			StatisticsSliceVariation,
			StatisticsSliceDefault,
			SwitchSlice,
			SwitchSliceDefaultPrimarySubsectionItem,
			SwitchSliceDefaultPrimary,
			SwitchSliceVariation,
			SwitchSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimaryTestimonialsItem,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault,
			ToolsSlice,
			ToolsSliceDefaultPrimaryToolsItem,
			ToolsSliceDefaultPrimary,
			ToolsSliceVariation,
			ToolsSliceDefault,
			VideoHeroSlice,
			VideoHeroSliceDefaultPrimary,
			VideoHeroSliceVariation,
			VideoHeroSliceDefault
		};
	}
}
